version: "3"

services:
  flask-sentiment:
    build: ./flask-sentiment
    container_name: sentiment-ai
    ports:
      - 5000:5000
  web-app:
    build: ./web
    container_name: sentiment-web
    ports:
      - 3000:3000